[[redirects]]
  from = "/skill/create"
  to = "/unauthorized"
  status = 302
  condition = '''
    !(window.isAdmin && window.isAdmin.value)
  '''

[[redirects]]
  from = "/skill/edit/:id"
  to = "/unauthorized"
  status = 302
  condition = '''
    !(window.isAdmin && window.isAdmin.value)
  '''

[[redirects]]
  from = "/posts/create"
  to = "/unauthorized"
  status = 302
  condition = '''
    !(window.isAdmin && window.isAdmin.value)
  '''

[[redirects]]
  from = "/posts/edit/:id"
  to = "/unauthorized"
  status = 302
  condition = '''
    !(window.isAdmin && window.isAdmin.value)
  '''

[[redirects]]
  from = "/project/create"
  to = "/unauthorized"
  status = 302
  condition = '''
    !(window.isAdmin && window.isAdmin.value)
  '''

[[redirects]]
  from = "/guestbook"
  to = "/guestbook"
  status = 200

[[redirects]]
  from = "/posts/:slug"
  to = "/posts/:slug"
  status = 200

[[redirects]]
  from = "/tag/:tag"
  to = "/tag/:tag"
  status = 200

[[redirects]]
  from = "/unauthorized"
  to = "/unauthorized"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
